### ISSUE TITLE
Cleanup fails with TooManyRequestsException.

### ISSUE THREAD

**Issue by aczire** [lumigo-io/SAR-Lambda-Janitor#37]
Cleanup fails with TooManyRequestsException.
`{
    "message": "retrying listAliases after error...",
    "function": "arn:aws:lambda:us-east-1:xxxxxxxxx:function:stg-xxxxx-xxxxx--xxxxxxxx-Zg5KOhlu8oeX",
    "errorName": "TooManyRequestsException",
    "errorMessage": "Rate exceeded",
    "stackTrace": "TooManyRequestsException: Rate exceeded\n    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)\n    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)\n    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)",
    "awsRegion": "us-east-1",
    "functionName": "serverlessrepo-lambda-janitor-Clean-m4tgnmdyQTPF",
    "functionVersion": "$LATEST",
    "functionMemorySize": "128",
    "level": 40,
    "sLevel": "WARN"
}`

**Comment by mebibou** [comment]
I have the same problem, the function never runs successfully. Has anyone been able to fix this issue?

**Comment by singhsoldier13** [comment]
+1

**Comment by ahudelson** [comment]
Same issue

**Comment by ewingate00** [comment]
+1
