### ISSUE TITLE
Unable to deploy via SAM. Getting error "Plugin 'ServerlessAppPlugin' raised an exception: AWS Region cannot be found"

### ISSUE THREAD

**Issue by afs25** [lumigo-io/SAR-Lambda-Janitor#61]
Hi, I'm trying to deploy SAR-Lambda-Janitor via a SAM template. I've added it to the Resources section of my SAM template:

Resources:
  SarLambdaJanitor:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/lambda-janitor
        SemanticVersion: 1.5.0
      Parameters:
        VersionsToKeep: 3

However, when I run:
$ sam build --debug -t ./template.yaml

I am seeing the error:
Plugin 'ServerlessAppPlugin' raised an exception: AWS Region cannot be found

I am not sure how to solve this. Any help would be much appreciated. Thank you!

**Comment by pedroGenio** [comment]
same error for SemanticVersion: 1.6.1

$ sam deploy --guided

`2024-04-16 11:06:26 Plugin 'ServerlessAppPlugin' raised an exception: AWS Region cannot be found
Traceback (most recent call last):
  File "samtranslator/plugins/sam_plugins.py", line 130, in act
  File "samtranslator/metrics/method_decorator.py", line 116, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 150, in on_before_transform_template
  File "samtranslator/region_configuration.py", line 48, in is_service_supported
samtranslator.translator.arn_generator.NoRegionFound: AWS Region cannot be found`
